'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class KnowledgeInputContent
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ShiftOS_TheRevival.KnowledgeInputContent", GetType(KnowledgeInputContent).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to aardvark
        '''albatross
        '''alligator
        '''alpaca
        '''ant
        '''anteater
        '''antelope
        '''ape
        '''armadillo
        '''ass
        '''baboon
        '''badger
        '''barracuda
        '''bat
        '''bear
        '''beaver
        '''bee
        '''bison
        '''boar
        '''buffalo
        '''butterfly
        '''camel
        '''caribou
        '''cat
        '''caterpillar
        '''cow
        '''chamois
        '''cheetah
        '''chicken
        '''chimpanzee
        '''chinchilla
        '''chough
        '''clam
        '''cobra
        '''cockroach
        '''cod
        '''cormorant
        '''coyote
        '''crab
        '''crane
        '''crocodile
        '''crow
        '''curlew
        '''deer
        '''dinosaur
        '''dog
        '''dogfish
        '''dolphin
        '''donkey
        '''dotterel
        '''dove
        '''dragonfly
        '''duck
        '''dugong
        '''dunlin
        '''eagle
        '''echidna
        '''eel
        '''eland
        '''elephant
        '''elephant seal
        '''elk
        '''emu        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Animals() As String
            Get
                Return ResourceManager.GetString("Animals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to afghanistan
        '''albania
        '''algeria
        '''andorra
        '''angola
        '''antigua and barbuda
        '''argentina
        '''armenia
        '''australia
        '''austia
        '''azerbaijan
        '''bahamas
        '''bahrain
        '''bangladesh
        '''barbados
        '''belarus
        '''belgium
        '''belize
        '''benin
        '''bhutan
        '''bolivia
        '''bosnia and herzegovina
        '''botswana
        '''brazil
        '''brunei
        '''bulgraia
        '''burkina faso
        '''burundi
        '''cambodia
        '''cameroon
        '''canada
        '''cape verde
        '''central african republic
        '''chad
        '''chile
        '''china
        '''colombia
        '''comoros
        '''democratic republic of the congo
        '''republic of the congocosta rica
        '''croatia
        '''cuba
        '''cyprus
        '''czechia
        '''denmark
        '''djibou [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Countries() As String
            Get
                Return ResourceManager.GetString("Countries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to apple
        '''apricot
        '''avocado
        '''banana
        '''breadfruit
        '''bilberry
        '''blackberry
        '''blackcurrant
        '''blueberry
        '''boysenberry
        '''cantaloupe
        '''currant
        '''cherry
        '''cherimoya
        '''chili
        '''cloudberry
        '''coconut
        '''damson
        '''date
        '''dragonfruit
        '''durian
        '''elderberry
        '''feijoa
        '''fig
        '''gooseberry
        '''grape
        '''grapefruit
        '''guava
        '''huckleberry
        '''honeydew
        '''jackfruit
        '''jambul
        '''jujube
        '''kiwi fruit
        '''kumquat
        '''legume
        '''lemon
        '''lime
        '''loquat
        '''lychee
        '''mango
        '''melon
        '''canary melon
        '''cantaloupe
        '''honeydew
        '''watermelon
        '''rock melon
        '''nectarine
        '''nut
        '''orange
        '''clementine
        '''mandarine
        '''tangerine
        '''p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Fruits() As String
            Get
                Return ResourceManager.GetString("Fruits", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
