'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ShiftOS_TheRevival.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.2.3.
        '''</summary>
        Friend ReadOnly Property CurrentVersion() As String
            Get
                Return ResourceManager.GetString("CurrentVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WARNING: READ BEFORE PLAYING!
        '''
        '''A very small percentage of individuals may experience epileptic seizures when 
        '''exposed to certain light patterns or flashing lights. Exposure to certain patterns or 
        '''backgrounds on a computer screen, or while playing video games, may induce an 
        '''epileptic seizure in these individuals. Certain conditions may induce previously 
        '''undetected epileptic symptoms even in persons who have no history of prior 
        '''seizures or epilepsy.
        '''
        '''If you, or anyone in your family, have an epil [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property epilepsy() As String
            Get
                Return ResourceManager.GetString("epilepsy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A basic command-line tool for simple calculation.
        '''
        '''example: 
        '''5*5+5
        '''8-3
        '''44/2.
        '''</summary>
        Friend ReadOnly Property man_bc() As String
            Get
                Return ResourceManager.GetString("man_bc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Changes directory to a selected one
        '''
        ''' [DIRECTORY] Name of directory you want to enter.
        '''</summary>
        Friend ReadOnly Property man_cd() As String
            Get
                Return ResourceManager.GetString("man_cd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clears all contents of the terminal.
        '''</summary>
        Friend ReadOnly Property man_clear() As String
            Get
                Return ResourceManager.GetString("man_clear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows the value of codepoint in your wallet.
        '''</summary>
        Friend ReadOnly Property man_codepoint() As String
            Get
                Return ResourceManager.GetString("man_codepoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes Background and Foreground color to a specific two Hexadecimal value
        '''
        '''[BG] Color for Terminal Background
        '''[FG] Color for Terminal Foreground such as text
        '''
        '''example: color 02.
        '''</summary>
        Friend ReadOnly Property man_color() As String
            Get
                Return ResourceManager.GetString("man_color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display available colors for ShiftOS.
        '''</summary>
        Friend ReadOnly Property man_colors() As String
            Get
                Return ResourceManager.GetString("man_colors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displays all subdirectories and files that are in the current directory
        '''
        '''example: dir.
        '''</summary>
        Friend ReadOnly Property man_dir() As String
            Get
                Return ResourceManager.GetString("man_dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Runs the &apos;Guess the Number&apos; application..
        '''</summary>
        Friend ReadOnly Property man_guess() As String
            Get
                Return ResourceManager.GetString("man_guess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows all commands available in the terminal and its brief explanation of action.
        '''</summary>
        Friend ReadOnly Property man_help() As String
            Get
                Return ResourceManager.GetString("man_help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displays informations about current session of Terminal such as current time, current application, current user, and current codepoint
        '''
        '''[OPTION]		Option to do certain things regarding the Infobar
        '''COLOR [BG][FG]	changes the infobar&apos;s color to the selected one
        '''[ON|OFF]		Turning infobar on or off
        '''.
        '''</summary>
        Friend ReadOnly Property man_infobar() As String
            Get
                Return ResourceManager.GetString("man_infobar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shows up a manual on each corresponding command and its example of action
        '''
        '''[COMMAND] Any command that you want to get the manual for
        '''
        '''Example: man help.
        '''</summary>
        Friend ReadOnly Property man_man() As String
            Get
                Return ResourceManager.GetString("man_man", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating a directory
        '''
        '''[DIRECTORY] Any directory you want to create.
        '''</summary>
        Friend ReadOnly Property man_mkdir() As String
            Get
                Return ResourceManager.GetString("man_mkdir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prints a corresponding text entered in the command.
        '''</summary>
        Friend ReadOnly Property man_print() As String
            Get
                Return ResourceManager.GetString("man_print", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display any current directory navigated on ShiftOS
        '''
        '''example: pwd.
        '''</summary>
        Friend ReadOnly Property man_pwd() As String
            Get
                Return ResourceManager.GetString("man_pwd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminate ShiftOS session and re-running the session.
        '''</summary>
        Friend ReadOnly Property man_reboot() As String
            Get
                Return ResourceManager.GetString("man_reboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleting a directory if there is no file present
        '''
        '''[DIRECTORY] Any directory you want to remove
        '''
        '''example: rmdir Windows.
        '''</summary>
        Friend ReadOnly Property man_rmdir() As String
            Get
                Return ResourceManager.GetString("man_rmdir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command-line system information tool for ShiftOS
        '''Ported from Neofetch.
        '''</summary>
        Friend ReadOnly Property man_shiftfetch() As String
            Get
                Return ResourceManager.GetString("man_shiftfetch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A software center for upgrading features in ShiftOS
        '''
        '''[OPTION] Shiftorium execute mode
        '''LIST    Printing a list of available upgrade in ShiftOS
        '''INFO    Displays informations such as description, instruction, and example command
        '''INSTALL Install the selected feature to ShiftOS (if the Codepoints are either equal or more to required)
        '''
        '''[featureName] Feature name
        '''
        '''Example: shiftorium install man, shiftorium info clear.
        '''</summary>
        Friend ReadOnly Property man_shiftorium() As String
            Get
                Return ResourceManager.GetString("man_shiftorium", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminate ShiftOS session.
        '''</summary>
        Friend ReadOnly Property man_shutdown() As String
            Get
                Return ResourceManager.GetString("man_shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displays current version of ShiftOS TheRevival.
        '''</summary>
        Friend ReadOnly Property man_ver() As String
            Get
                Return ResourceManager.GetString("man_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MenuBanner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuBanner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MenuBanner2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuBanner2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
